"use client";
import {useEffect,useState} from "react";
type S={weight:string,goal:string,steps:string,pushups:string,reminder:string,water:number};
const base:S={weight:"72",goal:"Build muscle + discipline",steps:"10000",pushups:"50",reminder:"19:30",water:5};
export default function Home(){const[s,setS]=useState(base);const[tab,setTab]=useState("Today");useEffect(()=>{const x=localStorage.getItem("edin-os");if(x)setS(JSON.parse(x))},[]);function edit(k:keyof S,v:string|number){const n={...s,[k]:v};setS(n);localStorage.setItem("edin-os",JSON.stringify(n))}async function notify(){if(!("Notification"in window))return alert("Ky browser nuk i suporton notifications.");const p=await Notification.requestPermission();if(p==="granted")new Notification("EDIN OS",{body:"Reminders u aktivizuan. Hajde Edin 🔥",icon:"/icon.svg"})}
return <main><header><div><span className="tag">EDIN OS · PERSONAL PERFORMANCE</span><h1>Hajde Edin.</h1><p>Sot fitohet me veprime te vogla.</p></div><div className="avatar">E</div></header><section className="score"><div><span>DAILY SCORE</span><b>78</b><small>/100</small></div><div><strong>Je ne rruge te mire.</strong><p>Workout + hapa + fokus. Mbylle diten forte.</p></div></section><div className="tabs">{["Today","Train","Progress","Life","AI"].map(x=><button onClick={()=>setTab(x)} className={tab===x?"on":""} key={x}>{x}</button>)}</div>
{tab==="Today"&&<><h2>Sot</h2><div className="grid"><Box title="HAPAT"><input inputMode="numeric" value={s.steps} onChange={e=>edit("steps",e.target.value)}/><small>target ditor</small></Box><Box title="PESHA"><input inputMode="decimal" value={s.weight} onChange={e=>edit("weight",e.target.value)}/><small>kg aktuale</small></Box><Box title="POMPAT"><input inputMode="numeric" value={s.pushups} onChange={e=>edit("pushups",e.target.value)}/><small>target sot</small></Box><Box title="UJE"><button className="bigbtn" onClick={()=>edit("water",Math.min(12,s.water+1))}>{s.water}/8</button><small>prek per +1 gote</small></Box></div><section className="goal"><span>QELLIMI AKTUAL</span><input value={s.goal} onChange={e=>edit("goal",e.target.value)}/><p>Ruhet automatikisht.</p></section></>}
{tab==="Train"&&<section className="sheet"><span>PLANI I SOTEM · PUSH</span><h2>45 min · Strength</h2>{[["Bench Press","4 × 8","50 kg"],["Incline Dumbbell","3 × 10","16 kg"],["Shoulder Press","3 × 8","20 kg"],["Push-ups","3 × max","Body"]].map(x=><div className="exercise" key={x[0]}><div><b>{x[0]}</b><small>{x[1]}</small></div><button>{x[2]}</button></div>)}<p className="hint">Qellimi: progressive overload. Rrite peshen gradualisht vetem me forme te mire.</p></section>}
{tab==="Progress"&&<section className="sheet"><span>PROGRESS</span><h2>Dokumento rrugen.</h2><div className="metric"><b>{s.weight} kg</b><small>Pesha aktuale</small></div><div className="metric"><b>12 dite</b><small>Streak</small></div><button className="primary">+ Shto progress photo</button></section>}
{tab==="Life"&&<section className="sheet"><span>REMINDERS</span><h2>Kur don me t'nguc?</h2><label>Ora<input type="time" value={s.reminder} onChange={e=>edit("reminder",e.target.value)}/></label><button className="primary" onClick={notify}>Aktivizo notifications</button><div className="lifeitem"><b>Focus / Dopamine</b><p>45 min deep work · pa scroll para workout-it.</p></div><div className="lifeitem"><b>Nutrition</b><p>Protein ne cdo vakt · uje · ushqim i thjeshte.</p></div></section>}
{tab==="AI"&&<section className="sheet"><span>EDIN AI</span><h2>Asistenti yt personal.</h2><div className="chat">Edin, targeti yt eshte {s.goal.toLowerCase()}. Sot fokusohu te workout-i, {s.steps} hapa dhe gjumi ne kohe.</div><input className="ask" placeholder="Pyete EDIN AI..." /><button className="primary">Dergo</button></section>}
<nav>{["Today","Train","Progress","Life","AI"].map(x=><button onClick={()=>setTab(x)} className={tab===x?"active":""} key={x}><b>{x==="Today"?"●":x==="Train"?"↗":x==="Progress"?"⌁":x==="Life"?"◇":"✦"}</b><span>{x==="AI"?"Edin AI":x}</span></button>)}</nav></main>}
function Box({title,children}:{title:string,children:React.ReactNode}){return <div className="box"><span>{title}</span>{children}</div>}