"use client";
import {useEffect,useState} from "react";
type S={name:string,weight:string,goal:string,days:string,place:string,reminder:string,pushups:string};
const base:S={name:"Edin",weight:"72",goal:"Build muscle",days:"4",place:"Fitness",reminder:"19:30",pushups:"50"};
const plan=[["Bench Press","4 × 8","Chest · strength"],["Incline Dumbbell Press","3 × 10","Upper chest"],["Shoulder Press","3 × 8","Shoulders"],["Triceps Pushdown","3 × 12","Triceps"],["Push-ups","3 × max","Finisher"]];
export default function Home(){const[s,setS]=useState(base);const[tab,setTab]=useState("Today");const[msg,setMsg]=useState("");const[chat,setChat]=useState<string[]>([]);
useEffect(()=>{const x=localStorage.getItem("edin-profile");if(x)setS(JSON.parse(x))},[]);
function edit(k:keyof S,v:string){const n={...s,[k]:v};setS(n);localStorage.setItem("edin-profile",JSON.stringify(n))}
function ask(){if(!msg.trim())return;const q=msg.toLowerCase();let a="Edin, per qellimin tand fokusohu ne konsistence, forme te mire dhe progres gradual.";if(q.includes("hanger")||q.includes("ushq"))a="Edin, per muskuj: protein ne cdo vakt, karbohidrate rreth stervitjes, fruta/perime dhe uje. Zgjedh p.sh. veze + buke, pule + oriz, kos grek + fruta.";if(q.includes("pompa"))a="Edin, mos shko direkt ne maksimum cdo here. Beni 3 sete me forme te paster dhe le 1–2 reps ne rezerve. Kur behet lehte, rrite volumin.";if(q.includes("sot")||q.includes("ushtru"))a="Edin, sot e ke Push Day: gjoks, shpatulla dhe triceps. Nise me Bench Press dhe regjistro peshen/reps.";setChat(c=>[...c,"Ti: "+msg,"EDIN AI: "+a]);setMsg("")}
async function notify(){if(!("Notification"in window))return alert("Notifications nuk suportohen ketu.");const p=await Notification.requestPermission();if(p==="granted")new Notification("EDIN OS",{body:s.name+", koha per stervitje. Mos e le per neser 💪",icon:"/icon.svg"})}
return <main><header><div><span className="tag">EDIN OS · FITNESS COACH</span><h1>Hajde {s.name}.</h1><p>Plan. Stervitje. Progres.</p></div><div className="avatar">E</div></header><section className="score"><div><span>KETE JAVE</span><b>3</b><small> / {s.days}</small></div><div><strong>Edhe {Math.max(0,Number(s.days)-3)} stervitje.</strong><p>Consistency streak · 3 jave</p></div></section><div className="tabs">{["Today","Train","Progress","Coach","Setup"].map(x=><button onClick={()=>setTab(x)} className={tab===x?"on":""} key={x}>{x}</button>)}</div>
{tab==="Today"&&<><h2>Sot · Push Day</h2><section className="sheet"><span>TARGETI</span><h2>{s.goal}</h2><p className="hint">{s.days} here ne jave · {s.place} · {s.weight} kg</p>{plan.slice(0,3).map(x=><div className="exercise" key={x[0]}><div><b>{x[0]}</b><small>{x[2]}</small></div><button>{x[1]}</button></div>)}</section><div className="grid"><Box title="POMPAT"><input inputMode="numeric" value={s.pushups} onChange={e=>edit("pushups",e.target.value)}/><small>target · shkruje numrin</small></Box><Box title="FITNESS"><strong className="number">3/{s.days}</strong><small>sterivitje kete jave</small></Box></div></>}
{tab==="Train"&&<section className="sheet"><span>PROGRAMI · PUSH DAY</span><h2>Strength + Hypertrophy</h2>{plan.map(x=><div className="exercise" key={x[0]}><div><b>{x[0]}</b><small>{x[2]}</small></div><button>{x[1]}</button></div>)}<button className="primary">Nise stervitjen</button></section>}
{tab==="Progress"&&<section className="sheet"><span>PROGRESI</span><h2>Po nderton konsistence.</h2><div className="metric"><b>3 / {s.days}</b><small>Kete jave</small></div><div className="metric"><b>12</b><small>Stervitje kete muaj</small></div><div className="metric"><b>{s.weight} kg</b><small>Pesha aktuale</small></div><button className="primary">+ Regjistro stervitjen</button></section>}
{tab==="Coach"&&<section className="sheet"><span>EDIN AI COACH</span><h2>Pyet per stervitje ose ushqim.</h2><div className="chatlog">{chat.length?chat.map((x,i)=><div className={x.startsWith("EDIN")?"bot":"me"} key={i}>{x}</div>):<div className="bot">Edin, jom ketu. Me pyet p.sh. “qka me ushtru sot?”, “qka me hanger?”, ose “sa pompa me bo?”</div>}</div><div className="composer"><input value={msg} onChange={e=>setMsg(e.target.value)} onKeyDown={e=>e.key==="Enter"&&ask()} placeholder="Shkruj Coach-it..."/><button onClick={ask}>Dergo</button></div></section>}
{tab==="Setup"&&<section className="sheet"><span>PERSONALIZIMI</span><h2>Ky eshte sistemi yt.</h2><label>Emri<input value={s.name} onChange={e=>edit("name",e.target.value)}/></label><label>Pesha (kg)<input inputMode="decimal" value={s.weight} onChange={e=>edit("weight",e.target.value)}/></label><label>Qellimi<input value={s.goal} onChange={e=>edit("goal",e.target.value)}/></label><label>Sa here ne jave?<input inputMode="numeric" value={s.days} onChange={e=>edit("days",e.target.value)}/></label><label>Ku ushtron?<select value={s.place} onChange={e=>edit("place",e.target.value)}><option>Fitness</option><option>Shtepi</option><option>Te dyja</option></select></label><label>Ora e reminder-it<input type="time" value={s.reminder} onChange={e=>edit("reminder",e.target.value)}/></label><button className="primary" onClick={notify}>Aktivizo reminder-at</button></section>}
<nav>{["Today","Train","Progress","Coach","Setup"].map(x=><button onClick={()=>setTab(x)} className={tab===x?"active":""} key={x}><b>{x==="Today"?"●":x==="Train"?"↗":x==="Progress"?"⌁":x==="Coach"?"✦":"⚙"}</b><span>{x==="Coach"?"Edin AI":x}</span></button>)}</nav></main>}
function Box({title,children}:{title:string,children:React.ReactNode}){return <div className="box"><span>{title}</span>{children}</div>}